apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-node-hello
  labels:
    app: ms-node-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-node-hello
  template:
    metadata:
      labels:
        app: ms-node-hello
    spec:
      containers:
      - name: ms-node-hello
        image: local/ms-node-hello
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: ms-node-hello
  labels:
    app: ms-node-hello
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30304
      protocol: TCP
      name: http
  selector:
    app: ms-node-hello

