apiVersion: skaffold/v1alpha2
kind: Config
build:
  local: { skipPush: true }
  artifacts:
  - imageName: local/ms-node-hello
    docker: {}
  googleCloudBuild: null
  kaniko: null
deploy:
  helm: null
  kubectl:
    manifests:
    - ./kube-*.yml
